Vagrant.configure("2") do |config|
  
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.hostname = "node01.example.com"
  
  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", "768"]
  end

end
