Vagrant.configure("2") do |config|
  
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.hostname = "node01.example.com"
  
  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provision :shell, :inline => "echo 'Provisioning mit der Shell ...'"
  config.vm.provision :shell, :inline => "sudo apt-get update"
  config.vm.provision :shell, :path => "scripts/install-apache.sh"

end
