Vagrant.configure("2") do |config|
  
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define :app01 do |app01|
    app01.vm.hostname = "app01.example.com"
    app01.vm.network :private_network, ip: "192.168.33.11"
  end
  config.vm.define :db01 do |db01|
    db01.vm.hostname = "db01.example.com"
    db01.vm.network :private_network, ip: "192.168.33.12"
  end

end
